# general cfg
image_flip:             True
max_depth:              15
domain:                 rgb

# ros topics
vizTopic:               /viplanner/viz_path_rgb
imgTopic:               /camera/color/image_raw/compressed
infoTopic:              /camera/color/camera_info
goalTopic:              /mp_waypoint
pathTopic:              /viplanner/path

# frame ids
robot_frame:            base
odom_frame:             odom
