# planning
main_freq:              10
image_flip:             False
conv_dist:              0.5
max_depth:              15
overlap_ratio_thres:    0.80
depth_zero_ratio_thres: 0.6
# network model
model_save:             models
# mmdet
m2f_model_path:         models/mask2former_r50_lsj_8x2_50e_coco-panoptic_20220326_224516-11a44721.pth
m2f_cfg_file:           /home/second_self_dog/.local/lib/python3.8/site-packages/mmdet/.mim/configs/mask2former/mask2former_r50_8xb2-lsj-50e_coco-panoptic.py

# ros topics
depth_topic:            /camera/depth/image_rect_raw
depth_info_topic:       /camera/depth/camera_info
rgb_topic:              /camera/color/image_raw/compressed
rgb_info_topic:         /camera/color/camera_info
goal_topic:             /mp_waypoint
path_topic:             /viplanner/path
m2f_timer_topic:        /viplanner/m2f_timer
depth_uint_type:        True
compressed:             True
# frame ids
robot_id:               odom  # also adjust in path_follower.launch
world_id:               odom
# fear reaction
is_fear_act:            False
buffer_size:            3
angular_thread:         0.3
track_dist:             0.5
# smart joystick
joyGoal_scale:          2.5
